name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: x64
          cache: pip

      - name: Install UPX
        run: choco install upx

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        env:
          PYTHONOPTIMIZE: 2
        run: |
          pyinstaller --onefile --noconsole --clean --strip --upx-dir "C:\Program Files\upx" --name AirfoilDesigner run_gui.py
      - name: Compress with UPX
        run: upx --best --force --lzma dist\AirfoilDesigner.exe

      - name: List dist folder
        run: dir dist\

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: AirfoilDesigner
          path: dist/AirfoilDesigner.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: AirfoilDesigner

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}

      - name: Upload EXE asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/AirfoilDesigner.exe
          asset_name: AirfoilDesigner.exe
          asset_content_type: application/octet-stream
