name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: x64
          cache: pip

      - name: Install UPX
        run: choco install upx

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        env:
          PYTHONOPTIMIZE: 2
        run: pyinstaller --onefile --noconsole --clean --strip --upx-dir "C:\Program Files\upx" --name AirfoilDesigner run_gui.py

      - name: Compress with UPX
        run: upx --force --best --lzma dist\AirfoilDesigner.exe

      - name: List dist folder
        run: dir dist\

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: AirfoilDesigner
          path: dist/AirfoilDesigner.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: AirfoilDesigner

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: AirfoilDesigner/AirfoilDesigner.exe
