name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: x64
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        shell: pwsh
        run: |
          # locate CasADi .pyd dynamically
          $casadi_pyd = Get-ChildItem -Path .\.venv\Lib\site-packages\casadi\_casadi*.pyd | Select-Object -First 1

          # PyInstaller command
          pyinstaller --clean --onefile --noconsole --icon=img/favicon.ico --name AirfoilDesigner `
            --hidden-import casadi._casadi `
            --add-binary "$($casadi_pyd.FullName);casadi" `
            --add-binary ".\.venv\Lib\site-packages\OCP\*;OCP" `
            --add-binary ".\.venv\Lib\site-packages\cadquery\*;cadquery" `
            run_gui.py

      - name: Zip EXE
        run: powershell Compress-Archive -Path dist\AirfoilDesigner.exe -DestinationPath dist\AirfoilDesigner.zip -Force

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/AirfoilDesigner.zip
