name: Build and Release Windows EXE

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: x64
          cache: pip
      
      - name: Create virtual environment and everything else in one step
        run: |
          python -m venv .venv
          .\.venv\Scripts\Activate.ps1
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

          # locate CasADi .pyd dynamically
          $casadi_pyd = Get-ChildItem -Path .\.venv\Lib\site-packages\_casadi*.pyd | Select-Object -First 1
      
          pyinstaller --onefile --noconsole --clean --icon=img/favicon.ico `
            --hidden-import "OCP" `
            --hidden-import "casadi._casadi" `
            --add-binary "$($casadi_pyd.FullName);casadi" `
            --name AirfoilDesigner run_gui.py
            - name: Activate venv & install dependencies
              shell: powershell
              
      - name: Zip EXE
        run: powershell Compress-Archive -Path dist\AirfoilDesigner.exe -DestinationPath dist\AirfoilDesigner.zip -Force

      - name: Create or Update GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/AirfoilDesigner.zip
