name: Build and Release Windows EXEs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python (${{ matrix.arch }})
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: ${{ matrix.arch }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Package EXE (${{ matrix.arch }})
        run: pyinstaller --onefile --clean --strip --noconsole --name AirfoilDesigner-${{ matrix.arch }} run_gui.py

      - name: List dist folder
        run: dir dist\

      - name: Upload build artifact (${{ matrix.arch }})
        uses: actions/upload-artifact@v3
        with:
          name: AirfoilDesigner-${{ matrix.arch }}
          path: dist/AirfoilDesigner-${{ matrix.arch }}.exe

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download x86 build
        uses: actions/download-artifact@v3
        with:
          name: AirfoilDesigner-x86

      - name: Download x64 build
        uses: actions/download-artifact@v3
        with:
          name: AirfoilDesigner-x64

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload x86 asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: AirfoilDesigner-x86/AirfoilDesigner-x86.exe
          asset_name: AirfoilDesigner-x86.exe
          asset_content_type: application/octet-stream

      - name: Upload x64 asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: AirfoilDesigner-x64/AirfoilDesigner-x64.exe
          asset_name: AirfoilDesigner-x64.exe
          asset_content_type: application/octet-stream
